import { z } from "zod";

/**
 * Shared Zod schema for Create + Edit rider forms.
 * riderId is auto-generated by the backend so it's never part of the form.
 * IsActive defaults to true on create; on edit the user can toggle it off.
 */
export const riderSchema = z.object({
  riderName: z
    .string()
    .min(1, "rider name is required")
    .max(100, "rider name must be under 100 characters"),
    shortName: z
    .string()
    .min(1, "rider short name is required")
    .max(5, "rider short name must be under 100 characters"),
  isActive: z.boolean(),
});

export type riderFormValues = z.infer<typeof riderSchema>;
